#!/bin/bash

# are we root
if [ $EUID != 0 ]; then
   echo "sudo $0 $@"
   sudo "$0" "$@"
   exit $?
fi

lab_required() {
  PKG=""
  type virt-manager >/dev/null 2>&1 || PKG="$PKG virt-manager"
  type virt-vieuwer >/dev/null 2>&1 || PKG="$PKG virt-viewer"
  type virsh        >/dev/null 2>&1 || PKG="$PKG libvirt-client"
  if [ "${PKG}" != "" ]; then
    dnf install -y $PKG || yum install -y $PKG
  fi
}

lab_purgeconfig() {
  echo "----------------------------------"
  echo "-- purgeing virtual environment --"
  echo "----------------------------------"
  virsh destroy labipa
  virsh destroy server1
  virsh destroy server2
  virsh undefine labipa
  virsh undefine server1
  virsh undefine server2
  virsh net-destroy labvms
  virsh net-undefine labvms
  virsh pool-destroy vmdata
  virsh pool-undefine vmdata
}

lab_initialization() {
  echo "----------------------------------------"
  echo "-- initialization virtual environment --"
  echo "----------------------------------------"
  virsh net-define libvirtdefines/network_labvms.xml
  virsh net-autostart labvms
  virsh net-start labvms
  sleep 2
  virsh pool-define libvirtdefines/pool_vmdata.xml
  virsh pool-autostart vmdata
  virsh pool-start vmdata
  sleep 2
  virsh define libvirtdefines/labipa.xml
  virsh define libvirtdefines/server1.xml
  virsh define libvirtdefines/server2.xml

  # set correct ip
  BRIDGEDEV_FROM_LABVMS=$(virsh net-dumpxml labvms | grep "bridge name" | cut -f 2 -d \')
  nmcli connection modify "${BRIDGEDEV_FROM_LABVMS}" ipv4.addresses '192.168.4.1, 192.168.4.2'
}

lab_usage() {
  echo "usage: $0 [purge|init]"
}

###
### MAIN
###

# See how we were called.
case "$1" in
  purge)
    lab_required
    lab_purgeconfig
    ;;
  init)
    lab_required
    lab_initialization
    ;;
  *)
    lab_usage
    exit 1
    ;;
esac
