#!/bin/bash

# are we root
if [ $EUID != 0 ]; then
   echo "sudo $0 $@"
   sudo "$0" "$@"
   exit $?
fi

lab_required() {
  type virt-manager >/dev/null 2>&1 || yum install virt-manager -y
}

lab_purgeconfig() {
  virsh destroy labipa
  virsh destroy server1
  virsh destroy server2
  echo "purgeing labvms"
  virsh net-destroy labvms
  virsh net-undefine labvms
  virsh undefine labipa
  virsh undefine server1
  virsh undefine server2
}

lab_initialization() {
  echo "init labvms"
  virsh net-define libvirtdefines/labvms.xml
  virsh net-autostart labvms
  virsh net-start labvms
  sleep 2
  virsh define libvirtdefines/labipa.xml
  virsh define libvirtdefines/server1.xml
  virsh define libvirtdefines/server2.xml

  # set correct ip
  BRIDGEDEV_FROM_LABVMS=$(virsh net-dumpxml labvms | grep "bridge name" | cut -f 2 -d \')
  nmcli connection modify "${BRIDGEDEV_FROM_LABVMS}" ipv4.addresses '192.168.4.1, 192.168.4.2'
}

lab_usage() {
  echo "usage: $0 [purge|init]"
}

###
### MAIN
###

# See how we were called.
case "$1" in
  purge)
    lab_required
    lab_purgeconfig
    ;;
  init)
    lab_required
    lab_purgeconfig
    lab_initialization
    ;;
  *)
    lab_usage
    exit 1
    ;;
esac
