#!/bin/bash
#
# labvms - helper script for deployment of pre-defined virtual machines
#
# - self-service to quick reinitiate a fresh virtual machine
#
# usage: labvms [labipa|server1|server2] [unzip|convert|setdisk|fulldeploy]"
#
# first argument the vmname: labipa, server1 or server2 (the name as it's defined in libvirt)
# second argument is the action: unzip, convert, setdisk or fulldeploy
#
# - unzip      : unzip the file
# - convert    : convert the vmdk into qcow2 image
# - setdisk    : only set the disks to the initial version. (this effectily 'resets' the virtual machine)
# - fulldeploy : all of the above
#
# requirements;
# - libvirt configured virtual machines
# - directory /vmdata is currently hardcoded
# - /vmdata should have the labipa-3.0.3.zip, server1-ova3.zip and server2-ova3.zip
#

# are we root
if [ $EUID != 0 ]; then
   echo "sudo $0 $@"
   sudo "$0" "$@"
   exit $?
fi

IMAGESPATH="/vmdata"

lab_required() {
  type unzip    >/dev/null 2>&1 || yum install unzip -y
  type qemu-img >/dev/null 2>&1 || yum install qemu-img -y
  test -d /vmdata || lab_setupdatadir
  find /vmdata -name '*.inprogress' -print
}

lab_checksum() {
  cd /vmdata
  echo -n "Checksum: "
  echo "${ZIPMD5} ${ZIPZIP}" | md5sum -c -
}

lab_setupdatadir() {
  echo "exiting, path /vmdata missing ..."
  exit 1
}

lab_unzip() {
  cd /vmdata
  rm -Rf "${ZIPDIR}"
  unzip "${ZIPZIP}"
}

lab_convert() {
  cd /vmdata
  test -d ${ZIPDIR} || lab_unzip
  for vmdk in `find ${ZIPDIR} -name '*.vmdk'`;
    do
      filetarget=$(basename "$vmdk")
      filetarget="${filetarget%.*}"
      echo "converting ${vmdk} to ${filetarget}.qcow2"
      qemu-img convert -p -O qcow2 ${vmdk} "${ZIPDIR}/${filetarget}.qcow2.inprogress"
      echo "qemu-img convert exitcode: $?"
  done
}

lab_destroyvm() {
  echo "Force shutdown ${ZIPVMNAME} ..."
  sleep 3
  virsh destroy "${ZIPVMNAME}" >/dev/null 2>&1
}

lab_startvm() {
  echo "Starting ${ZIPVMNAME} ..."
  virsh start "${ZIPVMNAME}"
}

lab_stopvm() {
  echo "Shutdown ${ZIPVMNAME} ..."
  virsh shutdown "${ZIPVMNAME}"
}

lab_movelibvirt() {
  cd /vmdata
  for diskimage in `find ${ZIPDIR} -name '*.qcow2.inprogress'`;
  do
    filetarget=$(basename "$diskimage")
    filetarget="${filetarget%.*}"
    # strips all before '-' server1_3.1.2.3.4-disk1.qcow2 becomes disk1.qcow2
    filetargetvm=$(echo $filetarget | cut -d "-" -f 2-)
    mv ${diskimage} "${IMAGESPATH}/${ZIPVMNAME}-$filetargetvm"
    echo "Diskimage ${ZIPVMNAME}-${filetargetvm} deployed"
  done
}

lab_usage() {
  echo "usage: $0 [labipa|server1|server2] [unzip|convert|setdisk|fulldeploy]"
}

###
### MAIN
###

# See how we were called.
case "$1" in
  labipa)
    ZIPZIP="labipa-3.0.3.zip"
    ZIPDIR="labipa-3.0.3"
    ZIPVMNAME="labipa"
    ZIPMD5="ebb81fe6d972fdfc6bd27341bfe725fd"
    ;;
  server1)
    ZIPZIP="server1-ova3.zip"
    ZIPDIR="server1-ova3"
    ZIPVMNAME="server1"
    ZIPMD5="d52d581279114183aeaca821508545a7"
    ;;
  server2)
    ZIPZIP="server2-ova3.zip"
    ZIPDIR="server2-ova3"
    ZIPVMNAME="server2"
    ZIPMD5="8ac04bec5d6918c3ac8965093ef4208a"
    ;;
  *)
    lab_usage
    exit 1
    ;;
esac

case "$2" in
  unzip)
    lab_required
    lab_checksum
    lab_unzip
    ;;
  convert)
    lab_required
    lab_convert
    ;;
  setdisk)
    lab_required
    lab_destroyvm
    lab_movelibvirt
    ;;
  fulldeploy)
    lab_required
    lab_checksum
    lab_unzip
    lab_convert
    lab_destroyvm
    lab_movelibvirt
    ;;
  fulldeploystart)
    lab_required
    lab_checksum
    lab_unzip
    lab_convert
    lab_destroyvm
    lab_movelibvirt
    lab_startvm
    ;;
  shutdown)
    lab_stopvm
    ;;
  *)
    lab_usage
    exit 1
    ;;
esac
